### ISSUE TITLE
Panel can overflow the edge of the screen

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [velade/dynamic-panel#4]
Hi! First off, I just found this extension and love it! I noticed an issue though upon first installing it - in certain conditions, the panel can extend off the edge of the screen! Below are some screenshots to show what happens:

| Extension Settings | My Desktop |
| --------------------------- | ----------------- |
| ![image](https://github.com/user-attachments/assets/fb5f78a0-a1f0-46a9-98d7-fd342138d27c) | ![image](https://github.com/user-attachments/assets/54c7f1db-ca44-4ca9-a853-86fa72800db6) |

When there is a window near the panel, it looks fine:
![image](https://github.com/user-attachments/assets/35b3059c-c3e3-489f-b076-b185745d7cfb)

I've forked this project and tweaked some code in order to fix this, but it may have side effects that you don't want (for example, you can't have the panel offset from the top, whilst still touching one or both sides of the screen), so I'll submit a pull request and let you decide if you want to merge it or not. A potential solution might be to make the margin configurable per-side, which I'd be more than happy to implement if you would like me to.

Thanks again for the great extension!

EDIT: My Pull Request is #5

**Comment by velade** [comment]
Thanks for the feedback, I'll try to fix this later, but I won't merge your pull because I'm providing 100% width to allow the panel to be 100% wide, and your solution forces the base subtraction Margins.
What I should fix is ​​not the floating_width problem, but the fact that 100% of the time the margin should not be generated on the left (in fact I can't reproduce this problem on my machine) It seems to be because wayland handles it differently than x11 Yes, I haven't had time to adapt to wayland yet.

**Comment by velade** [comment]
Oh, I think I know the cause of this problem: in center alignment mode, the left and right margins of the panel are calculated by themselves, so there will be no overflow problem, but when you select left alignment, the left margin is fixed to Base-Margin, so when your Floating-Width setting is too high, it will cause overflow. This is just a problem of inappropriate setting combination, not a technical problem. You just need to set the Floating-Margin a little smaller (I use 99%), and then choose to center it.

I know separate margins would be a better design, but this would conflict with the "Width" and I need to think about how to optimize this experience. Because I don’t want to have to tell users that when you set the width, you also need to consider whether to adjust the left and right margins. For example, some people may want to fill the screen width, but find that setting the width to 100% has no effect. This only makes it more confusing.
